
name: CI - Build & Test

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    environment: github
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache-dependency-path: web/package-lock.json
          cache: 'npm'

      - run: |
          cd web
          npm ci
          npm run build

      # - uses: dtolnay/rust-toolchain@1.85.0
      # - uses: tauri-apps/tauri-action@v0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
      #     TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
      #   with:
      #     includeRelease: true
      #     tagName: ${{ github.ref_name }}
      #     releaseName: "Release ${{ github.ref_name }}"
      #     releaseBody: "See the assets below to download this version and install."
      #     releaseDraft: false
      #     prerelease: false

      # - name: Setup Pages
      #   uses: actions/configure-pages@v3

      # - name: Install cargo-llvm-cov
      #   uses: taiki-e/install-action@cargo-llvm-cov
        
      # - name: code coverage
      #   run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      #   working-directory: ./game

      # - name: push to codecov
      #   uses: codecov/codecov-action@v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./game/lcov.info

      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: "./web/dist"

  # deploy:
  #   needs: build
  #   uses: ./.github/workflows/gh-pages.yml