
name: CI - Build & Test

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache
        id: cache-web
        uses: actions/cache@v4
        with:
          path: |
            web/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/web/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # - name: Setup Pages
      #   uses: actions/configure-pages@v3

      # - name: Install cargo-llvm-cov
      #   uses: taiki-e/install-action@cargo-llvm-cov
        
      # - name: code coverage
      #   run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      #   working-directory: ./game

      # - name: push to codecov
      #   uses: codecov/codecov-action@v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./game/lcov.info

      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: "./web/dist"

  # deploy:
  #   needs: build
  #   uses: ./.github/workflows/deploy.yml